name: go build s3-streaming-listner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            go: '1.17'
            path_name: s3-streaming-lister
            bin_name: ./s3-streaming-lister-linux

          - platform: [ macos-latest ]
            #'self-hosted', 'macOS', 'X64']
            # macos-latest
            go: '1.17'
            path_name: s3-streaming-lister
            bin_name: ./s3-streaming-lister-macos

          - platform: [ windows-latest ]
            #'self-hosted', 'Windows', 'X64']
            go: '1.17'
            path_name: s3-streaming-lister.exe
            bin_name: ./s3-streaming-lister-win.exe

    name: Build Go ${{ matrix.go }} ${{ join(matrix.platform, ',') }} s3-streaming-lister
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Build Plain Executable for ${{ matrix.os }}
        run: |
          make test
          make build BIN_NAME=${{ matrix.bin_name }} GITCOMMIT=${{ github.sha }}

      # - env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   name: Build Docker for ${{ matrix.os }}
      #   if: ${{ matrix.platform == 'ubuntu-latest' }}
      #   run: |
      #     echo $GITHUB_TOKEN | docker login docker.pkg.github.com/ -u mabels --password-stdin
      #     GITCOMMIT=$(git rev-parse --short HEAD)
      #     echo Docker build $GITCOMMIT
      #     docker build . --tag s3-streaming-lister/${{ matrix.bin_name }}:$GITCOMMIT
      #     docker tag s3-streaming-lister/${{ matrix.bin_name }}:$GITCOMMIT docker.pkg.github.com/mabels/s3-streaming-lister/s3-streaming-lister:$GITCOMMIT-amd64
      #     docker push docker.pkg.github.com/mabels/s3-streaming-lister/s3-streaming-lister:$GITCOMMIT-amd64
