
name: Build - s3-streaming-lister

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build 
      run: |
        go build

