name: Build Eimer-Kette

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.19.0"

    - name: Go Setup
      run: |
        go get ./...
        go mod tidy

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
        CGO_ENABLED=0 go build -ldflags="-s -w -X main.Version='{{.Version}}' -X main.GitCommit={{.Commit}}" -o ./ -v ./...
        ./eimer-kette --version

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKERFILE: Dockerfile
        GOVERSION: ${{ steps.setup-go.outputs.go-version }}

#  docker-build:
#    runs-on: ubuntu-latest
#    name: Create Docker 
#    if: startsWith(github.ref, 'refs/tags/v')
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Building
#        run: |
#          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u mabels --password-stdin
#          export VERSION=$(basename ${{ github.ref }})
#          docker build -t eimer-kette:${{ github.sha }} .
#          docker tag eimer-kette:${{ github.sha }} ghcr.io/mabels/eimer-kette:$VERSION
#          docker push ghcr.io/mabels/eimer-kette:$VERSION
#          docker tag eimer-kette:${{ github.sha }} ghcr.io/mabels/eimer-kette:latest
#          docker push ghcr.io/mabels/eimer-kette:latest
